### PR TITLE
Tic-tac-toe Milestone 1: Project setup

### PR DESCRIPTION
**Pull request by Daniduran-dev**
We have created: 
- master and development branches
- lib folder
- bin folder
- lib/.gitkeep file
- bin/main.rb excutable file main

### CODE REVIEW

**Comment by santiago-dev96** [comment]
# Pull Request under review by @santiago-rodrig (TSE)

**Review by santiago-dev96 — CHANGES_REQUESTED** [review]
# Changes Required 🔧 

You completed all the requirements for milestone 1, but remember that for every project you must first set up the linters, this project has no linters configured yet.

## Optional

- Add a basic `README.md` file with instructions on how to set up the project locally, this should not have instructions on how to play the game obviously, leave that for milestone 4.

## What to do now?

Implement the required changes and submit another CRR.

You can find me in slack as **srodrig**, happy coding! :wave:

**Comment by Daniduran-dev** [comment]
We have encountered errors false detected by rubocop:
- Use single quotes
- Add final newline

Both are corrected but rubocop still detects them. We tried to disable those errors in main.rb but rubocop detected the disable line as a new error so we had to modify rubocop.yml and now everything is working as it should do.

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi Team 👋

Nice work so far on this and implementing the changes requested in the previous review.

- [x] There are two `main` files in the `bin` folder. Please remove this: `main` and leave this `main.rb`.

### **I trust you will fix this before merging.**

### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

**Pull request merged**
